// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZoF_6NeWc0sr7JAPbypKSlTvipO_jnu4',
    appId: '1:501511615301:web:525dfa903ed515ca84042c',
    messagingSenderId: '501511615301',
    projectId: 'flutter-login-4b8e6',
    authDomain: 'flutter-login-4b8e6.firebaseapp.com',
    storageBucket: 'flutter-login-4b8e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOlW0RIdEgXWcXruzcZozPOi-pM0RGnjs',
    appId: '1:501511615301:android:3dd7d0c247267d8e84042c',
    messagingSenderId: '501511615301',
    projectId: 'flutter-login-4b8e6',
    storageBucket: 'flutter-login-4b8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa7NC19OG3kerL_5fRa8jSb0rZhnHgQA8',
    appId: '1:501511615301:ios:7a253a2b1210cbba84042c',
    messagingSenderId: '501511615301',
    projectId: 'flutter-login-4b8e6',
    storageBucket: 'flutter-login-4b8e6.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa7NC19OG3kerL_5fRa8jSb0rZhnHgQA8',
    appId: '1:501511615301:ios:7a253a2b1210cbba84042c',
    messagingSenderId: '501511615301',
    projectId: 'flutter-login-4b8e6',
    storageBucket: 'flutter-login-4b8e6.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZoF_6NeWc0sr7JAPbypKSlTvipO_jnu4',
    appId: '1:501511615301:web:c8205666e7d546e784042c',
    messagingSenderId: '501511615301',
    projectId: 'flutter-login-4b8e6',
    authDomain: 'flutter-login-4b8e6.firebaseapp.com',
    storageBucket: 'flutter-login-4b8e6.firebasestorage.app',
  );
}
